website/models.py
from . import db
from datetime import datetime

# Define database model
class RemoteRequest(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    ip = db.Column(db.String(15), nullable=False)
    isp = db.Column(db.Text, nullable=False)
    city = db.Column(db.Text, nullable=False)
    country = db.Column(db.Text, nullable=False)
    method = db.Column(db.String(7), nullable=False)
    agent = db.Column(db.String(256), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

    def __repr__(self):
        return f"RemoteRequest('{self.ip}')"
    
    def serialize(self):
        return {
            "id": self.id,
            "ip": self.ip,
            "isp": self.isp,
            "city": self.city,
            "country": self.country,
            "method": self.method,
            "agent": self.agent,
            "created_at": str(self.created_at)
        }

website/__init__.py
from flask import Flask
from flask_moment import Moment
from werkzeug.middleware.proxy_fix import ProxyFix
from flask_sqlalchemy import SQLAlchemy
from os import path
from .config import *

# Create and define database
db = SQLAlchemy()
db_name = "database.db"

# Define filepaths
current_dir = path.dirname(__file__)
parent_dir = path.dirname(current_dir)
static_dir = path.join(current_dir, 'static')
db_dir = path.join(parent_dir, "instance")
db_path = path.join(db_dir, db_name)
swagger_dir = path.join(static_dir, "swagger")
swagger_path = path.join(swagger_dir, "swagger.json")

# Create application
def create_app():
    app = Flask(__name__)
    app.config["SECRET_KEY"] = config.SECRET_KEY                                            # Secret key for session cookies
    app.config['SQLALCHEMY_DATABASE_URI'] = config.SQLALCHEMY_DATABASE_URI.format(db_path)  # Location/type of db
    app.config["DEBUG"] = config.DEBUG                                                      # Debug mode on for dev, off for prod
    app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1, x_host=1, x_prefix=1)         # Used to interpret data from the proxy (Nginx in this case)
    db.init_app(app)
    moment = Moment(app)

    # Import and register webpage blueprints
    from .views import views
    app.register_blueprint(views, url_prefix="/")

    # Import and register database
    from .models import RemoteRequest
    with app.app_context():
        db.create_all()     # Only creates db if it doesn't already exist
    
    # Import and register API
    from .api import api
    api.init_app(app)

    return app

website/views.py
from flask import Blueprint, render_template, request, jsonify, redirect, url_for, Response
from sqlalchemy.sql import func
from datetime import datetime
from .models import RemoteRequest
from .external_requests import lookup_geoip
from . import db

views = Blueprint("views", __name__)

# Index
# When a request is made here, it looks up and stores
# the request information
@views.route("/")
def home():
    request_ip = request.remote_addr
    request_geoip = lookup_geoip(request_ip)
    request_method = request.method
    request_agent = request.user_agent
    new_request = RemoteRequest(ip=str(request_ip),
                                isp=str(request_geoip["isp"]),
                                city=str(request_geoip["city"]),
                                country=str(request_geoip["country"]),
                                method=str(request_method),
                                agent=str(request_agent),
                                created_at=func.now())
    db.session.add(new_request)
    db.session.commit()
    
    return render_template("index.html")

# Page that displays the data in the db
@views.route("/request_log")
def score():
    return render_template("request_log.html")

# Swagger API documentation
@views.route("/apidocs")
def api_docs():
    return render_template("swaggerui.html")

# Queries all data in the db and displays in plain old json format
@views.route("/json")
def get_json():
    ids = RemoteRequest.query.all()
    data = []
    for id in ids:
        data.append(id.serialize())
    return jsonify(data)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">
        <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}" />
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='stylesheets/main.css') }}" />
        {{ moment.include_moment() }}
        {% block optional_header %}{% endblock %}
    </head>
    <body>
        <div id="page_container">
            <!-- Header section. Site logo and top navbar. -->
            <div id="header">
                <header>
                    <a href="/">
                        <img src="{{ url_for('static', filename='images/logo.png') }}" alt="logo" class="logo" id="logo"/>
                    </a>
                    <nav class="top_nav">
                        <ul>
                            <li>
                                <a href="/">Home</a>
                            </li>
                            <li>
                                <a href="/request_log">Request Log</a>
                            </li>
                            <li>
                                <a href="/apidocs">API</a>
                            </li>
                            <li>
                                <a href="/json">JSON</a>
                            </li>
                        </ul>
                    </nav>
                </header>
            </div>

            <!-- Container to separate the header from the main content -->
            <div id="top_splitter">
            </div>

            <!-- Main page content -->
            <div id="content_wrap">
                {% block content %}{% endblock %}
            </div>
        
            <!-- Footer section. Copyright and links. -->
            <div class="footer_container">
                <footer id="footer">
                    <div class="footer_content">
                        <span class="footer_copyright">
                            &copy; Copyright {{ moment().format("YYYY") }} by Al Robison.&nbsp
                        </span>
                        <span class="footer_links">
                            <ul>
                                <li>
                                    <a href="https://github.com/gtrspctr">Github</a>
                                </li>
                            </ul>
                        </span>
                    </div>
                </footer>
            </div>
        </div>
    </body>
</html>

website/templates/index.html
{% extends "base.html" %}

{% block title %}
    Home | alrobison.com
{% endblock %}

{% block content %}
    <div id="title">
        <center>
            <h1>Creepy, Crawly Bots</h1>
        </center>
    </div>
    <div id="body">
        <p>
            Over my <i>modest</i> amount of time spent tinkering with web design,
            I've noticed an alarming amount of web requests hit my servers. The first
            time I noticed it, it made me feel contaminated. I felt unease and apprehension.
            I thought a hacker was trying to gain access to my server!
            But nothing ever happened.
        </p>
        <p>
            Later, a second request come in - This time from a different IP
            address. Tentatively, I looked up the IP's geolocation. Well, I don't know 
            what I expected to see, but it turned out to be a typical ISP in an ordinary,
            nondescript city.
        </p>
        <p>
            Huh. How about that.
        </p>
        <p>
            I had heard that bots are constantly scanning the internet - The emphasis
            always being that they are looking for open ports and vulnerabilities to
            take advantage of. And yeah, there definitely are those. But it turns out
            there are so many more bots! The more I saw, the more I wondered, "What
            the heck <i>are</i> all these requests? And why?"
        </p>
        <p>
            Well, I don't have the answer for every request. But I decided to start
            logging them in a database so I can display them in a nice, visible list.
        </p>
        <p>
            So that's what this site is. It basically only exists to see what requests
            it receives, and it stores these requests in a table for everyone to see!
            Head on over to the '<a href="/request_log">Requests Log</a>' page to take
            a look. The log shows the IP, the ISP it belongs to, the city, the country,
            the method (what <i>kind</i> of request), the agent (what type of device
            or software made the request), and the timestamp. Thanks to
            <a href="https://ip-api.com" target="_blank" rel="noopener noreferrer">
                IP-API.com <sup>&#x2197;</sup>
            </a>
            for the geolocation info.
        </p>
        <p>
            Oh. And I also <a href="/apidocs">made an API</a> where you can
            query/create/manipulate the data because I wanted to learn how that worked.
            Do whatever you want with it, I don't care. There will always be more bot
            requests.
        </p>
    </div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}

{% block title %}
    alrobison.com
{% endblock %}

{% block content %}
<form method="POST"
    <center>
        <h3>Login</h1>
    </center>
    <p>
        <div class=:"form-group">
            <label for="email">Email Address:</label>
            <input 
                type="email"
                class="form-control"
                id="email"
                name="email"
                placeholder="Enter email"
            />
        </div>
        <div class=:"form-group">
            <label for="password">Password:</label>
            <input 
                type="password"
                class="form-control"
                id="password"
                name="password"
                placeholder="Enter password"
            />
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Login</button>
    </p>
</form>
{% endblock %}

website/templates/request_log.html
{% extends "base.html" %}

{% block title %}
    Request Log | alrobison.com
{% endblock %}

{% block content %}
    <center>
        <h1>Here is a log of all requests that have been made to this site!</h1>
    </center>
    <div>
        <table id="request_log">
            <caption>
                <h2>Request Log</h2>
            </caption>

            <thead>
                <tr>
                    <th style="text-align: center" onclick="sortColumn('ip')">IP</th>
                    <th style="text-align: center" onclick="sortColumn('isp')">ISP</th>
                    <th style="text-align: center" onclick="sortColumn('city')">City</th>
                    <th style="text-align: center" onclick="sortColumn('country')">Country</th>
                    <th style="text-align: center" onclick="sortColumn('method')">Method</th>
                    <th style="text-align: center" onclick="sortColumn('agent')">Agent</th>
                    <th style="text-align: center" onclick="sortColumn('created_at')">Timestamp</th>
                </tr>
            </thead>

            <tbody id="request_log_TableBody"></tbody>
            
        </table>
        <div id="pagination-container"></div>
    </div>

    <script src="{{ url_for('static', filename='scripts/getRequestLogData.js') }}"></script>
{% endblock %}

website/templates/signup.html
{% extends "base.html" %}

{% block title %}
    alrobison.com
{% endblock %}

{% block content %}
<form method="POST"
    <center>
        <h3>Sign Up</h1>
    </center>
    <p>
        <div class=:"form-group">
            <label for="email">Email Address:</label>
            <input 
                type="email"
                class="form-control"
                id="email"
                name="email"
                placeholder="Enter email"
            />
        </div>
        <div class=:"form-group">
            <label for="first_name">First Name:</label>
            <input 
                type="text"
                class="form-control"
                id="first_name"
                name="first_name"
                placeholder="Enter first name"
            />
        </div>
        <div class=:"form-group">
            <label for="first_name">Last Name:</label>
            <input 
                type="text"
                class="form-control"
                id="last_name"
                name="last_name"
                placeholder="Enter last name"
            />
        </div>
        <div class=:"form-group">
            <label for="first_name">Password:</label>
            <input 
                type="password"
                class="form-control"
                id="password"
                name="password"
                placeholder="Enter password"
            />
        </div>
        <div class=:"form-group">
            <label for="first_name">Repeat Password:</label>
            <input 
                type="password"
                class="form-control"
                id="repeat_password"
                name="repeat_password"
                placeholder="Confirm password"
            />
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Submit</button>
    </p>
</form>
{% endblock %}

website/templates/swaggerui.html
{% extends "base.html" %}

{% block title %}
    Home | alrobison.com
{% endblock %}

{% block optional_header %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='stylesheets/swagger-ui.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='stylesheets/swagger-index.css') }}" />
{% endblock %}

{% block content %}
    <div id="swagger-ui" openapi-url="{{ url_for('static', filename='swagger/swagger.json') }}"></div>
    <script src="{{ url_for('static', filename='scripts/swagger-ui-bundle.js') }}" charset="UTF-8"> </script>
    <script src="{{ url_for('static', filename='scripts/swagger-ui-standalone-preset.js') }}" charset="UTF-8"> </script>
    <script src="{{ url_for('static', filename='scripts/swagger-initializer.js') }}" charset="UTF-8"> </script>
{% endblock %}

website/templates/unknown.html
{% extends "base.html" %}

{% block title %}
    alrobison.com
{% endblock %}

{% block content %}
    <center>
        <h1>Page request not recognized!!</h1>
        <h1><a href="{{ url_for('views.home') }}">Click here to go back home.</a></h1>
    </center>
{% endblock %}